version: '3.9'
services:
    collabora:
        image: collabora/code
        ports:
            - '9980:9980'
        tty: true
        environment:
            aliasgroup1: 'https://nextcloud.team-crystal.ch:443'
        cap_add:
            - 'MKNOD'
        restart: always
        container_name: collabora
